# Generated by Django 4.2.26 on 2025-11-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='stripe_checkout_session_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('stripe_checkout_session_id', 'product')},
        ),
    ]
